---
title: "NBA Voting"
author: "McCade Pearson"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggparliament)
library(hoopR)
library(tidyverse)
library(ggtext)
library(gt)
library(ggforce)
library(showtext)
library(sysfonts)
options(scipen = 99)

Teams <- hoopR::espn_nba_teams()
```

```{r Theme, warning = FALSE, message = FALSE, include = FALSE}
McCadeP8_theme_colors <- c(
  background = '#0D1117',   # dark slate gray (background)
  text       = '#F0F3F5',   # very light gray (text)
  panel      = '#1C1F26',   # near-black with blue hint (panel)
  border     = '#3E92CC',   # strong blue (border)
  strip_text = '#0D1117',   # matches background (strip text on light facet)
  lighter    = '#C3DDFD',   # baby blue
  light      = '#6FB1FC',   # sky blue
  medium     = '#326DA8',   # Jazz navy
  dark       = '#1D3557'    # deep indigo/navy
)

McCadeP8_palette <- c(
  '#C3DDFD', '#F94144', '#6A4C93', '#F9C74F', '#43AA8B',
  '#577590', '#F3722C', '#277DA1', '#264653'
)

## McCade Pearson
## theme_McCadeP8
## Date Created: June 10, 2025

# THEME COLOR PALETTE --------------------------------------

#' McCadeP8 Inspired Theme Color Palette
#'
#' @format character vector of hex code strings
#' @export
#' @concept McCadeP8
#'
McCadeP8_theme_colors <- c(
  background = '#0D1117',
  text       = '#F0F3F5',
  panel      = '#1C1F26',
  border     = '#3E92CC',
  strip_text = '#0D1117',
  lighter    = '#C3DDFD',
  light      = '#6FB1FC',
  medium     = '#326DA8',
  dark       = '#1D3557'
)

# DISCRETE COLOR PALETTE -----------------------------------

#' McCadeP8 Inspired Color Palette
#'
#' @format character vector of hex code strings
#' @export
#' @concept McCadeP8
#'
McCadeP8_palette <- c(
  '#C3DDFD', '#F94144', '#6A4C93', '#F9C74F', '#43AA8B',
  '#577590', '#F3722C', '#277DA1', '#264653'
)

# MAIN THEME ------------------------------------------------

#' McCadeP8 Inspired Theme
#'
#' @param McCadeP8_font should `theme_McCadeP8` use custom font? Default is `TRUE`.
#' @param ... additional parameters to pass to `ggplot2::theme()`
#'
#' @return a `ggplot2` `theme` object
#' @export
#' @concept McCadeP8
#'
theme_McCadeP8 <- function(McCadeP8_font = TRUE, ...) {

  # Load custom Google Font
  font_family <- ifelse(McCadeP8_font, "Barlow Semi Condensed", "sans")
  if (McCadeP8_font) {
  font_add_google(name = "Barlow Semi Condensed", family = "Barlow Semi Condensed")
  showtext_auto()
  }

  # Define the theme
  ggplot2::theme(
    plot.background = element_rect(fill = McCadeP8_theme_colors["background"], color = NA),
    panel.background = element_rect(fill = McCadeP8_theme_colors["panel"], color = NA),
    panel.border = element_rect(color = McCadeP8_theme_colors["border"], fill = NA, linewidth = 1.2),
    panel.grid.major = element_line(color = "#2D3748", size = 0.25),
    panel.grid.minor = element_blank(),
    
    text = element_text(color = McCadeP8_theme_colors["text"], family = font_family),
    title = element_text(size = 20, face = "bold", hjust = 0.5),
    axis.title = element_text(size = 17),
    axis.text = element_text(size = 13, color = McCadeP8_theme_colors["text"]),
    axis.ticks = element_line(color = McCadeP8_theme_colors["border"], linewidth = 1),
    
    legend.background = element_rect(fill = McCadeP8_theme_colors["panel"], color = NA),
    legend.text = element_text(size = 12),
    legend.title = element_text(size = 14, face = "bold"),
    
    strip.background = element_rect(fill = McCadeP8_theme_colors["lighter"], colour = McCadeP8_theme_colors["border"]),
    strip.text = element_text(colour = McCadeP8_theme_colors["strip_text"], size = 10)
  )
}

# COLOR SCALES ---------------------------------------------

#' McCadeP8 Inspired Color Scales
#'
#' @param ... Additional arguments to pass to `ggplot2::binned_scale` for `_b`,
#' `ggplot2::scale_[fill/color]_gradient` for `_c`, or `ggplot2::discrete_scale`
#' for `_d`
#'
#' @rdname scale_McCadeP8
#' @export
scale_color_McCadeP8_c <- function(...) {
  ggplot2::scale_color_gradient(..., low = McCadeP8_theme_colors["light"], high = McCadeP8_theme_colors["dark"])
}

#' @rdname scale_McCadeP8
#' @export
scale_fill_McCadeP8_c <- function(...) {
  ggplot2::scale_fill_gradient(..., low = McCadeP8_theme_colors["light"], high = McCadeP8_theme_colors["dark"])
}

#' @rdname scale_McCadeP8
#' @export
scale_color_McCadeP8_b <- function(...) {
  if (!requireNamespace('scales', quietly = TRUE)) {
    stop('This function requires the `scales` R package.')
  }
  ramp <- scales::colour_ramp(c(McCadeP8_theme_colors["light"], McCadeP8_theme_colors["dark"]))
  ggplot2::binned_scale('color', 'McCadeP8', palette = ramp, ...)
}

#' @rdname scale_McCadeP8
#' @export
scale_fill_McCadeP8_b <- function(...) {
  if (!requireNamespace('scales', quietly = TRUE)) {
    stop('This function requires the `scales` R package.')
  }
  ramp <- scales::colour_ramp(c(McCadeP8_theme_colors["light"], McCadeP8_theme_colors["dark"]))
  ggplot2::binned_scale('fill', 'McCadeP8', palette = ramp, ...)
}

#' @rdname scale_McCadeP8
#' @export
scale_color_McCadeP8_d <- function(...) {
  ggplot2::discrete_scale(aesthetics = 'color',
                          palette = rot_pal(McCadeP8_palette), ...)
}

#' @rdname scale_McCadeP8
#' @export
scale_fill_McCadeP8_d <- function(...) {
  ggplot2::discrete_scale(aesthetics = 'fill',
                          palette = rot_pal(McCadeP8_palette), ...)
}

# Aliases
#' @rdname scale_McCadeP8
#' @export
scale_colour_McCadeP8_d <- scale_color_McCadeP8_d
#' @rdname scale_McCadeP8
#' @export
scale_colour_McCadeP8_c <- scale_color_McCadeP8_c
#' @rdname scale_McCadeP8
#' @export
scale_colour_McCadeP8_b <- scale_color_McCadeP8_b
```


```{r}
MVPVoting <- read.csv("MVPVoting.csv")
MVPVoting <- MVPVoting %>%
  mutate(VoterNum = 1:n())


Players <- c("Shai Gilgeous-Alexander", "Nikola Jokic", "Giannis Antetokounmpo", "Jayson Tatum", "Donovan Mitchell", "LeBron James", "Cade Cunningham", "Anthony Edwards", "Stephen Curry", "Jalen Brunson", "James Harden", "Evan Mobley")
Team <- c("OKC", "DEN", "MIL", "BOS", "CLE", "LAL", "DET", "MIN", "GS", "NY", "LAC", "CLE")
PlayerTeam <- data.frame(Players,Team)
PlayerTeam <- PlayerTeam %>%
  group_by(Team) %>%
  mutate(PlayerNum = 1:n(),
         Max = max(PlayerNum)) %>%
  ungroup() %>%
  mutate(PlayerNum = ifelse(Max > 1, PlayerNum, NA)) %>%
  select(-Max)


String <- c("TEST")
ABC <- c(100)
BCD <- data.frame(String,ABC)
BaseData <- parliament_data(election_data = BCD, type = "semicircle", parl_rows = 5, party_seats = BCD$ABC)


Size <- 9
Size2 <- 7.8
Size3 <- 4.5
  
P1 <- BaseData %>%
  mutate(VoterNum = 1:n()) %>%
  left_join(MVPVoting, by = c('VoterNum')) %>%
  select(x, y, P1) %>%
  left_join(PlayerTeam, by = c('P1' = 'Players')) %>%
  left_join(Teams, by = c('Team' = 'abbreviation')) %>%
  mutate(color = paste0("#",color),
         color2 = paste0("#",alternate_color))

P1Plot <- ggplot(P1) +
  geom_point(aes(x = x, y = y), color = P1$color2, size = Size) +
  geom_point(aes(x = x, y = y), color = P1$color, size = Size2) +
  geom_text(aes(x = x, y = y, label = PlayerNum), color = P1$color2, size = Size3) +
  theme_McCadeP8() +
  labs(x = "", y = "", title = "1st Place Votes") +
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.line = element_blank(),
    panel.grid = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank())

P2 <- BaseData %>%
  mutate(VoterNum = 1:n()) %>%
  left_join(MVPVoting, by = c('VoterNum')) %>%
  select(x, y, P2) %>%
  left_join(PlayerTeam, by = c('P2' = 'Players')) %>%
  left_join(Teams, by = c('Team' = 'abbreviation')) %>%
  mutate(color = paste0("#",color),
         color2 = paste0("#",alternate_color))

P2Plot <- ggplot(P2) +
  geom_point(aes(x = x, y = y), color = P2$color2, size = Size) +
  geom_point(aes(x = x, y = y), color = P2$color, size = Size2) +
  geom_text(aes(x = x, y = y, label = PlayerNum), color = P2$color2, size = Size3) +
  theme_McCadeP8() +
  labs(x = "", y = "", title = "2nd Place Votes") +
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.line = element_blank(),
    panel.grid = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank())

P3 <- BaseData %>%
  mutate(VoterNum = 1:n()) %>%
  left_join(MVPVoting, by = c('VoterNum')) %>%
  select(x, y, P3) %>%
  left_join(PlayerTeam, by = c('P3' = 'Players')) %>%
  left_join(Teams, by = c('Team' = 'abbreviation')) %>%
  mutate(color = paste0("#",color),
         color2 = paste0("#",alternate_color))

P3Plot <- ggplot(P3) +
  geom_point(aes(x = x, y = y), color = P3$color2, size = Size) +
  geom_point(aes(x = x, y = y), color = P3$color, size = Size2) +
  geom_text(aes(x = x, y = y, label = PlayerNum), color = P3$color2, size = Size3) +
  theme_McCadeP8() +
  labs(x = "", y = "", title = "3rd Place Votes") +
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.line = element_blank(),
    panel.grid = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank())

P4 <- BaseData %>%
  mutate(VoterNum = 1:n()) %>%
  left_join(MVPVoting, by = c('VoterNum')) %>%
  select(x, y, P4) %>%
  left_join(PlayerTeam, by = c('P4' = 'Players')) %>%
  left_join(Teams, by = c('Team' = 'abbreviation')) %>%
  mutate(color = paste0("#",color),
         color2 = paste0("#",alternate_color))


P4Plot <- ggplot(P4) +
  geom_point(aes(x = x, y = y), color = P4$color2, size = Size) +
  geom_point(aes(x = x, y = y), color = P4$color, size = Size2) +
  geom_text(aes(x = x, y = y, label = PlayerNum), color = P4$color2, size = Size3) +
  theme_McCadeP8() +
  labs(x = "", y = "", title = "4th Place Votes") +
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.line = element_blank(),
    panel.grid = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank())

P5 <- BaseData %>%
  mutate(VoterNum = 1:n()) %>%
  left_join(MVPVoting, by = c('VoterNum')) %>%
  select(x, y, P5) %>%
  left_join(PlayerTeam, by = c('P5' = 'Players')) %>%
  left_join(Teams, by = c('Team' = 'abbreviation')) %>%
  mutate(color = paste0("#",color),
         color2 = paste0("#",alternate_color))


P5Plot <- ggplot(P5) +
  geom_point(aes(x = x, y = y), color = P5$color2, size = Size) +
  geom_point(aes(x = x, y = y), color = P5$color, size = Size2) +
  geom_text(aes(x = x, y = y, label = PlayerNum), color = P5$color2, size = Size3) +
  theme_McCadeP8() +
  labs(x = "", y = "", title = "5th Place Votes") +
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.line = element_blank(),
    panel.grid = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank())


Data_long <- MVPVoting %>%
  pivot_longer(cols = c("P1","P2","P3","P4","P5"), names_to = "Voted", values_to = "Votes") %>%
  mutate(Voted = case_when(
           Voted == "P1" ~ "1st",
           Voted == "P2" ~ "2nd", 
           Voted == "P3" ~ "3rd",
           Voted == "P4" ~ "4th",
           Voted == "P5" ~ "5th")) %>%
  group_by(Voted, Votes) %>%
  summarize(Total = n()) %>%
  ungroup()

P6Plot <- ggplot(Data_long, aes(x = Total, y = reorder(Votes,Total), fill = Voted)) +
  geom_col(color = "black") +
  scale_fill_manual(values = c("1st" = "#F9C74F", "2nd" = "#C3DDFD", "3rd" = "#F3722C", "4th" = "#6FB1FC", "5th" = "#43AA8B")) +
  theme_McCadeP8() +
  labs(title = "", x = "Votes", y = "") +
  theme(legend.position = c(0.95, 0.05), legend.justification = c(1, 0), legend.background = element_rect(linetype="solid", color = "white"))

grid.arrange(P1Plot, P6Plot, P2Plot, 
             P3Plot, P4Plot, P5Plot,
             ncol = 3, nrow = 2)
  
```

