import streamlit as st
import re as re
from data import get_weekly_scores, get_schedule, get_teams, get_logo, get_team_schedule, get_base_records, get_conf_records, get_RPI, get_team_stat, points_per_game

st.set_page_config(
    page_title = "Fantasy Hoops Crossover",
    page_icon = ":basketball:",
    layout = "wide")

teams = get_teams()
schedule = get_schedule()
scores = get_weekly_scores()
base_records = get_base_records(schedule, scores)
conf_records = get_conf_records(schedule, scores, teams)
RPI = get_RPI(base_records, schedule)
PPG = points_per_game(scores)

col1, col2, col3, col4 = st.columns([1, 1, 1, 1])

with col1:
    SelectedTeam1 = st.selectbox("Select Team 1", options=teams["Team"].tolist())
    st.image(get_logo(teams, SelectedTeam1))

    col5, col6 = st.columns([1,1,])
    with col5:
        st.metric(label = "Total Record", value = get_team_stat(base_records, SelectedTeam1, "Record"), delta = get_team_stat(base_records, SelectedTeam1, "Rank"), delta_color = "off", border = True)
        st.metric(label = "Quad 2 Record", value = get_team_stat(base_records, SelectedTeam1, "Record"), delta = get_team_stat(base_records, SelectedTeam1, "Record"), delta_color = "off", border = True)
        st.metric(label = "Quad 3 Record", value = get_team_stat(base_records, SelectedTeam1, "Record"), delta = get_team_stat(base_records, SelectedTeam1, "Record"), delta_color = "off", border = True)
        st.metric(label = "Ratings Power Index", value = get_team_stat(RPI, SelectedTeam1, "RPI"), delta = get_team_stat(RPI, SelectedTeam1, "RPI_Rk"), delta_color = "off", border = True)
        st.metric(label = "Points Per Week", value = get_team_stat(PPG, SelectedTeam1, "Avg Score"), delta = get_team_stat(base_records, SelectedTeam1, "PPG_Rk"), delta_color = "off", border = True)

    with col6:
        st.metric(label = "Conference Record", value = get_team_stat(conf_records, SelectedTeam1, "Record"), delta = get_team_stat(conf_records, SelectedTeam1, "Rank"), delta_color = "off", border = True)
        st.metric(label = "Quad 1 Record", value = get_team_stat(base_records, SelectedTeam1, "Record"), delta = get_team_stat(base_records, SelectedTeam1, "Record"), delta_color = "off", border = True)
        st.metric(label = "Quad 4 Record", value = get_team_stat(base_records, SelectedTeam1, "Record"), delta = get_team_stat(base_records, SelectedTeam1, "Record"), delta_color = "off", border = True)
        st.metric(label = "Strength of Schedule", value = get_team_stat(RPI, SelectedTeam1, "SOS"), delta = get_team_stat(RPI, SelectedTeam1, "SOS_Rk"), delta_color = "off", border = True)
        st.metric(label = "Weighted Recent", value = get_team_stat(base_records, SelectedTeam1, "Record"), delta = get_team_stat(base_records, SelectedTeam1, "Record"), delta_color = "off", border = True)

    st.subheader("Conference Games")
    CG1 = get_team_schedule(schedule, scores, teams, SelectedTeam1, "Conf")
    st.dataframe(CG1, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("OOC Tournament")
    OOC1 = get_team_schedule(schedule, scores, teams, SelectedTeam1, "OOC_Tourney")
    st.dataframe(OOC1, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Tip-Off Tournament")
    TOT1 = get_team_schedule(schedule, scores, teams, SelectedTeam1, "Tip-Off_Tourney")
    st.dataframe(TOT1, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Mascot Challenge")
    M1 = get_team_schedule(schedule, scores, teams, SelectedTeam1, "Mascot")
    st.dataframe(M1, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Luck of the Draw")
    LOTD1 = get_team_schedule(schedule, scores, teams, SelectedTeam1, "Luck")
    st.dataframe(LOTD1, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Cross-Conference Showdown")
    CC1 = get_team_schedule(schedule, scores, teams, SelectedTeam1, "Cross_Conf")
    st.dataframe(CC1, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Best of the Best")
    BOB1 = get_team_schedule(schedule, scores, teams, SelectedTeam1, "Best_Of_Best")
    st.dataframe(BOB1, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Rivalry Week")
    R1 = get_team_schedule(schedule, scores, teams, SelectedTeam1, "Rivalry")
    st.dataframe(R1, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Regional Rights")
    RR1 = get_team_schedule(schedule, scores, teams, SelectedTeam1, "Regional")
    st.dataframe(RR1, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Conference Tournament")
    CT1 = get_team_schedule(schedule, scores, teams, SelectedTeam1, "Conf_Tourney")
    st.dataframe(CT1, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})

with col2:
    SelectedTeam2 = st.selectbox("Select Team 2", options=teams["Team"].tolist())
    st.image(get_logo(teams, SelectedTeam2))
    st.metric(label = "Total Record", value = get_team_stat(base_records, SelectedTeam1, "Record"), delta = get_team_stat(base_records, SelectedTeam1, "Rank"), delta_color = "off", border = True)
    st.subheader("Conference Games")
    CG2 = get_team_schedule(schedule, scores, teams, SelectedTeam2, "Conf")
    st.dataframe(CG2, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("OOC Tournament")
    OOC2 = get_team_schedule(schedule, scores, teams, SelectedTeam2, "OOC_Tourney")
    st.dataframe(OOC2, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Tip-Off Tournament")
    TOT2 = get_team_schedule(schedule, scores, teams, SelectedTeam2, "Tip-Off_Tourney")
    st.dataframe(TOT2, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Mascot Challenge")
    M2 = get_team_schedule(schedule, scores, teams, SelectedTeam2, "Mascot")
    st.dataframe(M2, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Luck of the Draw")
    LOTD2 = get_team_schedule(schedule, scores, teams, SelectedTeam2, "Luck")
    st.dataframe(LOTD2, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Cross-Conference Showdown")
    CC2 = get_team_schedule(schedule, scores, teams, SelectedTeam2, "Cross_Conf")
    st.dataframe(CC2, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Best of the Best")
    BOB2 = get_team_schedule(schedule, scores, teams, SelectedTeam2, "Best_Of_Best")
    st.dataframe(BOB2, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Rivalry Week")
    R2 = get_team_schedule(schedule, scores, teams, SelectedTeam2, "Rivalry")
    st.dataframe(R2, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Regional Rights")
    RR2 = get_team_schedule(schedule, scores, teams, SelectedTeam2, "Regional")
    st.dataframe(RR2, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Conference Tournament")
    CT2 = get_team_schedule(schedule, scores, teams, SelectedTeam2, "Conf_Tourney")
    st.dataframe(CT2, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})

with col3:
    SelectedTeam3 = st.selectbox("Select Team 3", options=teams["Team"].tolist())
    st.image(get_logo(teams, SelectedTeam3))
    st.metric(label = "Total Record", value = get_team_stat(base_records, SelectedTeam1, "Record"), delta = get_team_stat(base_records, SelectedTeam1, "Rank"), delta_color = "off", border = True)
    st.subheader("Conference Games")
    CG3 = get_team_schedule(schedule, scores, teams, SelectedTeam3, "Conf")
    st.dataframe(CG3, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("OOC Tournament")
    OOC3 = get_team_schedule(schedule, scores, teams, SelectedTeam3, "OOC_Tourney")
    st.dataframe(OOC3, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Tip-Off Tournament")
    TOT3 = get_team_schedule(schedule, scores, teams, SelectedTeam3, "Tip-Off_Tourney")
    st.dataframe(TOT3, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Mascot Challenge")
    M3 = get_team_schedule(schedule, scores, teams, SelectedTeam3, "Mascot")
    st.dataframe(M3, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Luck of the Draw")
    LOTD3 = get_team_schedule(schedule, scores, teams, SelectedTeam3, "Luck")
    st.dataframe(LOTD3, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Cross-Conference Showdown")
    CC3 = get_team_schedule(schedule, scores, teams, SelectedTeam3, "Cross_Conf")
    st.dataframe(CC3, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Best of the Best")
    BOB3 = get_team_schedule(schedule, scores, teams, SelectedTeam3, "Best_Of_Best")
    st.dataframe(BOB3, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Rivalry Week")
    R3 = get_team_schedule(schedule, scores, teams, SelectedTeam3, "Rivalry")
    st.dataframe(R3, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Regional Rights")
    RR3 = get_team_schedule(schedule, scores, teams, SelectedTeam3, "Regional")
    st.dataframe(RR3, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Conference Tournament")
    CT3 = get_team_schedule(schedule, scores, teams, SelectedTeam3, "Conf_Tourney")
    st.dataframe(CT3, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})

with col4:
    SelectedTeam4 = st.selectbox("Select Team 4", options=teams["Team"].tolist())
    st.image(get_logo(teams, SelectedTeam4))
    st.metric(label = "Total Record", value = get_team_stat(base_records, SelectedTeam1, "Record"), delta = get_team_stat(base_records, SelectedTeam1, "Rank"), delta_color = "off", border = True)
    st.subheader("Conference Games")
    CG4 = get_team_schedule(schedule, scores, teams, SelectedTeam4, "Conf")
    st.dataframe(CG4, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("OOC Tournament")
    OOC4 = get_team_schedule(schedule, scores, teams, SelectedTeam4, "OOC_Tourney")
    st.dataframe(OOC4, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Tip-Off Tournament")
    TOT4 = get_team_schedule(schedule, scores, teams, SelectedTeam4, "Tip-Off_Tourney")
    st.dataframe(TOT4, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Mascot Challenge")
    M4 = get_team_schedule(schedule, scores, teams, SelectedTeam4, "Mascot")
    st.dataframe(M4, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Luck of the Draw")
    LOTD4 = get_team_schedule(schedule, scores, teams, SelectedTeam4, "Luck")
    st.dataframe(LOTD4, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Cross-Conference Showdown")
    CC4 = get_team_schedule(schedule, scores, teams, SelectedTeam4, "Cross_Conf")
    st.dataframe(CC4, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Best of the Best")
    BOB4 = get_team_schedule(schedule, scores, teams, SelectedTeam4, "Best_Of_Best")
    st.dataframe(BOB4, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Rivalry Week")
    R4 = get_team_schedule(schedule, scores, teams, SelectedTeam4, "Rivalry")
    st.dataframe(R4, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Regional Rights")
    RR4 = get_team_schedule(schedule, scores, teams, SelectedTeam4, "Regional")
    st.dataframe(RR4, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
    st.subheader("Conference Tournament")
    CT4 = get_team_schedule(schedule, scores, teams, SelectedTeam4, "Conf_Tourney")
    st.dataframe(CT4, width = "stretch", height = "content", row_height = 50, hide_index=True, placeholder="—", column_config={"Logo": st.column_config.ImageColumn("Opponent")})
