type_colors = {
    "Guaranteed": "#FCE5CD",   
    "Non-Guaranteed": "#F4CCCC",
    "Team": "#CFE2F3",         
    "Dead": "#D9D9D9",         
    "Unrestricted": "#D9D2E9", 
    "Restricted": "#CFFFFF", 
}

team_info = {
    "Albuquerque": {"bg": "#D72C2C", "text": "white", "logo": "https://pbs.twimg.com/media/Fxamop_aMAIM8OV?format=png&name=small", "nickname": "Armadillos"},
    "Anaheim": {"bg": "#DA0F10", "text": "white", "logo": "https://pbs.twimg.com/media/FxamoqBaQAAQSwY?format=png&name=small", "nickname": "Mice"},
    "Anchorage": {"bg": "#454B55", "text": "white", "logo": "https://pbs.twimg.com/media/FxamoqAaYAEpifP?format=png&name=small", "nickname": "Killer Whales"},
    "Austin": {"bg": "#040404", "text": "white", "logo": "https://pbs.twimg.com/media/Fxamop_aAAUl3cU?format=jpg&name=4096x4096", "nickname": "Bats"},
    "Baltimore": {"bg": "#00CED1", "text": "black", "logo": "https://pbs.twimg.com/media/Fxamr7daQAAhwSx?format=png&name=4096x4096", "nickname": "Blue Crabs"},
    "Birmingham": {"bg": "#853500", "text": "white", "logo": "https://pbs.twimg.com/media/Fxamr8GaMAE5xbG?format=png&name=small", "nickname": "Bandits"},
    "Boise": {"bg": "#744529", "text": "white", "logo": "https://pbs.twimg.com/media/Fxamr80aEAAWgO1?format=png&name=small", "nickname": "Spuds"},
    "Buffalo": {"bg": "#152238", "text": "white", "logo": "https://pbs.twimg.com/media/Fxamr7JaYAADNSj?format=png&name=small", "nickname": "Daredevils"},
    "Cincinnati": {"bg": "#FFEA61", "text": "black", "logo": "https://pbs.twimg.com/media/FxamtxqaMAAoWvU?format=png&name=small", "nickname": "Chili"},
    "Columbus": {"bg": "#CD7F32", "text": "white", "logo": "https://pbs.twimg.com/media/FxamtzbaUAEvyXi?format=png&name=4096x4096", "nickname": "Arches"},
    "Des Moines": {"bg": "#1B1E23", "text": "white", "logo": "https://pbs.twimg.com/media/FxamtzcaMAAPdlW?format=png&name=small", "nickname": "Racoons"},
    "El Paso": {"bg": "#F8EFAE", "text": "black", "logo": "https://pbs.twimg.com/media/FxamtxraQAANsYd?format=png&name=4096x4096", "nickname": "Vipers"},
    "Honolulu": {"bg": "#CDC0C0", "text": "black", "logo": "https://pbs.twimg.com/media/FxamvzcaUAAnl_g?format=png&name=4096x4096", "nickname": "Diamonds"},
    "Jacksonville": {"bg": "#36454F", "text": "white", "logo": "https://pbs.twimg.com/media/FxamvzoaIAAd9nF?format=png&name=4096x4096", "nickname": "Manatees"},
    "Kentucky": {"bg": "#663399", "text": "white", "logo": "https://pbs.twimg.com/media/Fxamv04aQAQl4UB?format=png&name=4096x4096", "nickname": "Thoroughbreds"},
    "Lansing": {"bg": "#B9EFE1", "text": "black", "logo": "https://pbs.twimg.com/media/Fxamv1ZacAAfxMM?format=png&name=4096x4096", "nickname": "Lagoon"},
    "Lincoln": {"bg": "#FC6A03", "text": "black", "logo": "https://pbs.twimg.com/media/Fxamx14aEAAyD29?format=png&name=4096x4096", "nickname": "Bully"},
    "Little Rock": {"bg": "#710193", "text": "white", "logo": "https://pbs.twimg.com/media/Fxamx2xaYAAqupS?format=png&name=small", "nickname": "Big Foot"},
    "Manchester": {"bg": "#D7F2FA", "text": "black", "logo": "https://pbs.twimg.com/media/Fxamx3nagAAZXCI?format=png&name=4096x4096", "nickname": "Trout"},
    "Nashville": {"bg": "#450012", "text": "white", "logo": "https://pbs.twimg.com/media/Fxamx01aMAAD8na?format=png&name=4096x4096", "nickname": "Strings"},
    "Pittsburgh": {"bg": "#F1F137", "text": "black", "logo": "https://pbs.twimg.com/media/Fxam0E7agAAc1zF?format=png&name=small", "nickname": "Bridge"},
    "Providence": {"bg": "#BF0A30", "text": "white", "logo": "https://pbs.twimg.com/media/Fxam0GKaQAAlzwx?format=png&name=4096x4096", "nickname": "Pilgrims"},
    "San Diego": {"bg": "#31439B", "text": "white", "logo": "https://pbs.twimg.com/media/Fxam0INacAIC29O?format=png&name=small", "nickname": "Seals"},
    "San Jose": {"bg": "#97EBF4", "text": "black", "logo": "https://pbs.twimg.com/media/Fxam0EvaIAAcI_3?format=png&name=4096x4096", "nickname": "Seagulls"},
    "Seattle": {"bg": "#006241", "text": "white", "logo": "https://pbs.twimg.com/media/Fxam1s5aAAIanao?format=png&name=4096x4096", "nickname": "Brew"},
    "St. Louis": {"bg": "#B7B1AE", "text": "black", "logo": "https://pbs.twimg.com/media/Fxam1ugaEAUkbUi?format=png&name=large", "nickname": "66ers"},
    "Tampa Bay": {"bg": "#FC8EAC", "text": "black", "logo": "https://pbs.twimg.com/media/F-yCFNbbkAAgIEt?format=jpg&name=4096x4096", "nickname": "Flamingos"},
    "Tulsa": {"bg": "#333333", "text": "white", "logo": "https://pbs.twimg.com/media/Fxam1s7aQAAiSsW?format=png&name=small", "nickname": "Tornado"},
    "Vancouver": {"bg": "#17780D", "text": "black", "logo": "https://pbs.twimg.com/media/Fxam4eaaMAAW6Pz?format=png&name=small", "nickname": "Forest"},
    "Vegas": {"bg": "#35654D", "text": "white", "logo": "https://pbs.twimg.com/media/Fxam4dlaIAIKnBb?format=png&name=4096x4096", "nickname": "Blackjack"},
}
