type_colors = {
    "Guaranteed": "#FCE5CD",   
    "Non-Guaranteed": "#F4CCCC",
    "Team": "#CFE2F3",         
    "Dead": "#D9D9D9",         
    "Unrestricted": "#D9D2E9", 
    "Restricted": "#CFFFFF", 
}

team_colors = {
    "Albuquerque": {"bg": "#D72C2C", "text": "white"},
    "Anaheim": {"bg": "#DA0F10", "text": "white"},
    "Anchorage": {"bg": "#454B55", "text": "white"},
    "Austin": {"bg": "#040404", "text": "white"},
    "Baltimore": {"bg": "#00CED1", "text": "black"},
    "Birmingham": {"bg": "#853500", "text": "white"},
    "Boise": {"bg": "#744529", "text": "white"},
    "Buffalo": {"bg": "#152238", "text": "white"},
    "Cincinnati": {"bg": "#FFEA61", "text": "black"},
    "Columbus": {"bg": "#CD7F32", "text": "white"},
    "Des Moines": {"bg": "#1B1E23", "text": "white"},
    "El Paso": {"bg": "#F8EFAE", "text": "black"},
    "Honolulu": {"bg": "#CDC0C0", "text": "black"},
    "Jacksonville": {"bg": "#36454F", "text": "white"},
    "Kentucky": {"bg": "#663399", "text": "white"},
    "Lansing": {"bg": "#B9EFE1", "text": "black"},
    "Lincoln": {"bg": "#FC6A03", "text": "black"},
    "Little Rock": {"bg": "#710193", "text": "white"},
    "Manchester": {"bg": "#D7F2FA", "text": "black"},
    "Nashville": {"bg": "#450012", "text": "white"},
    "Pittsburgh": {"bg": "#F1F137", "text": "black"},
    "Providence": {"bg": "#BF0A30", "text": "white"},
    "San Diego": {"bg": "#31439B", "text": "white"},
    "San Jose": {"bg": "#97EBF4", "text": "black"},
    "Seattle": {"bg": "#006241", "text": "white"},
    "St. Louis": {"bg": "#B7B1AE", "text": "black"},
    "Tampa Bay": {"bg": "#FC8EAC", "text": "black"},
    "Tulsa": {"bg": "#333333", "text": "white"},
    "Vancouver": {"bg": "#17780D", "text": "black"},
    "Vegas": {"bg": "#35654D", "text": "white"},
}
