type_colors = {
    "Guaranteed": "#FCE5CD",   
    "Non-Guaranteed": "#F4CCCC",
    "Team": "#CFE2F3",         
    "Dead": "#D9D9D9",         
    "Unrestricted": "#D9D2E9", 
    "Restricted": "#CFFFFF", 
}
team_info = {
    "Albuquerque": {"bg": "#D72C2C", "text": "white", "logo": "Pictures/Player_Images/Albuquerque.png"},
    "Anaheim": {"bg": "#DA0F10", "text": "white", "logo": "Pictures/Player_Images/Anaheim.png"},
    "Anchorage": {"bg": "#454B55", "text": "white", "logo": "Pictures/Player_Images/Anchorage.png"},
    "Austin": {"bg": "#040404", "text": "white", "logo": "Pictures/Player_Images/Austin.png"},
    "Baltimore": {"bg": "#00CED1", "text": "black", "logo": "Pictures/Player_Images/Baltimore.png"},
    "Birmingham": {"bg": "#853500", "text": "white", "logo": "Pictures/Player_Images/Birmingham.png"},
    "Boise": {"bg": "#744529", "text": "white", "logo": "Pictures/Player_Images/Boise.png"},
    "Buffalo": {"bg": "#152238", "text": "white", "logo": "Pictures/Player_Images/Buffalo.png"},
    "Cincinnati": {"bg": "#FFEA61", "text": "black", "logo": "Pictures/Player_Images/Cincinnati.png"},
    "Columbus": {"bg": "#CD7F32", "text": "white", "logo": "Pictures/Player_Images/Columbus.png"},
    "Des Moines": {"bg": "#1B1E23", "text": "white", "logo": "Pictures/Player_Images/Des Moines.png"},
    "El Paso": {"bg": "#F8EFAE", "text": "black", "logo": "Pictures/Player_Images/El Paso.png"},
    "Honolulu": {"bg": "#CDC0C0", "text": "black", "logo": "Pictures/Player_Images/Honolulu.png"},
    "Jacksonville": {"bg": "#36454F", "text": "white", "logo": "Pictures/Player_Images/Jacksonville.png"},
    "Kentucky": {"bg": "#663399", "text": "white", "logo": "Pictures/Player_Images/Kentucky.png"},
    "Lansing": {"bg": "#B9EFE1", "text": "black", "logo": "Pictures/Player_Images/Lansing.png"},
    "Lincoln": {"bg": "#FC6A03", "text": "black", "logo": "Pictures/Player_Images/Lincoln.png"},
    "Little Rock": {"bg": "#710193", "text": "white", "logo": "Pictures/Player_Images/Little Rock.png"},
    "Manchester": {"bg": "#D7F2FA", "text": "black", "logo": "Pictures/Player_Images/Manchester.png"},
    "Nashville": {"bg": "#450012", "text": "white", "logo": "Pictures/Player_Images/Nashville.png"},
    "Pittsburgh": {"bg": "#F1F137", "text": "black", "logo": "Pictures/Player_Images/Pittsburgh.png"},
    "Providence": {"bg": "#BF0A30", "text": "white", "logo": "Pictures/Player_Images/Providence.png"},
    "San Diego": {"bg": "#31439B", "text": "white", "logo": "Pictures/Player_Images/San Diego.png"},
    "San Jose": {"bg": "#97EBF4", "text": "black", "logo": "Pictures/Player_Images/San Jose.png"},
    "Seattle": {"bg": "#006241", "text": "white", "logo": "Pictures/Player_Images/Seattle.png"},
    "St. Louis": {"bg": "#B7B1AE", "text": "black", "logo": "Pictures/Player_Images/St. Louis.png"},
    "Tampa Bay": {"bg": "#FC8EAC", "text": "black", "logo": "Pictures/Player_Images/Tampa Bay.png"},
    "Tulsa": {"bg": "#333333", "text": "white", "logo": "Pictures/Player_Images/Tulsa.png"},
    "Vancouver": {"bg": "#17780D", "text": "black", "logo": "Pictures/Player_Images/Vancouver.png"},
    "Vegas": {"bg": "#35654D", "text": "white", "logo": "Pictures/Player_Images/Vegas.png"},
}
